version: "3.7"
services:
  web:
    image: saulteafarmer/pat-discord-lnbits-bot:latest  # Replace 'yourusername'
    restart: unless-stopped
    ports:
      - "3050:3050"
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    environment:
      - APP_DATA_DIR=/app/data
      - NODE_ENV=production
