version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: pat-discord-lnbits-bot_web_1
      APP_PORT: 3050
    
  web:
    image: saulteafarmer/pat-discord-lnbits-bot:latest
    restart: unless-stopped
    ports:
      - "3050:3050"
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    environment:
      - APP_DATA_DIR=/app/data
      - NODE_ENV=production
